baseURL: https://riabhana.netlify.app/
languageCode: en-us
title: Portfolio Website for Ria Bhana
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A website displaying some the data I have worked with and the findings I thought were interesting.
    title: Ria Bhana
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: rbhana.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (340) 7674-3647 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
    #  - icon: fa-twitter
     #   label: Twitter
     #   url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/ria.bhana
      #- icon: fa-instagram
       # label: Instagram
       # url: https://www.instagram.com/riabhana/?hl=en-gb
      - icon: fa-github
        label: GitHub
        url: https://github.com/riabhana/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/ria-bhana/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: A little bit about myself
        title: My Profile
        url: blogs/risk_return
      - image: CPI.jpg
        subtitle: Yearly Change of US CPI 
        title: CPI Component Analysis
        url: blogs/tempus
      - image: airbnb.jpg
        subtitle: Examining Price Trends for AirBnB 
        title: AirBnB in San Francisco
        url: blogs/airbnb
      - image: climate_change.jpg
        subtitle: Analysis of Global Temperature Deviations
        title: Climate Change
        url: blogs/Climate_Change
      - image: weight.jpg
        subtitle: examining the relationship weight and physical activity in high schoolers
        title: Youth Risk Behavior Analysis
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
